/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#1b1c1c',
        'primary-container': '#1c1b1b',
        'surface': '#fbf9f9',
        'on-error': '#ffffff',
        'tertiary-container': '#1a1c1b',
        'primary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed-variant': '#464746',
        'tertiary': '#000000',
        'surface-container-high': '#e9e8e7',
        'on-secondary-fixed-variant': '#5d4201',
        'on-tertiary-container': '#838482',
        'surface-bright': '#fbf9f9',
        'outline-variant': '#c4c7c7',
        'inverse-primary': '#c8c6c5',
        'on-secondary-fixed': '#261900',
        'secondary': '#775a19',
        'surface-container': '#efeded',
        'secondary-fixed': '#ffdea5',
        'background': '#fbf9f9',
        'tertiary-fixed': '#e3e2e0',
        'on-primary-fixed-variant': '#474746',
        'inverse-surface': '#303031',
        'outline': '#747878',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#c7c6c5',
        'surface-variant': '#e3e2e2',
        'on-secondary-container': '#785a1a',
        'on-primary-container': '#858383',
        'surface-tint': '#5f5e5e',
        'primary-fixed': '#e5e2e1',
        'inverse-on-surface': '#f2f0f0',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#444748',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#1b1c1c',
        'on-primary-fixed': '#1c1b1b',
        'surface-container-highest': '#e3e2e2',
        'secondary-fixed-dim': '#e9c176',
        'on-error-container': '#93000a',
        'surface-container-low': '#f5f3f3',
        'error': '#ba1a1a',
        'surface-dim': '#dbdad9',
        'primary': '#000000',
        'secondary-container': '#fed488',
        'on-tertiary-fixed': '#1a1c1b',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'section-gap': '120px',
        'margin-edge': '40px',
        unit: '8px',
        gutter: '24px',
      },
      fontFamily: {
        serif: ['"Noto Serif"', 'Georgia', 'serif'],
        sans: ['Manrope', 'system-ui', 'sans-serif'],
        'headline-lg': ['"Noto Serif"'],
        button: ['Manrope'],
        'body-md': ['Manrope'],
        'body-lg': ['Manrope'],
        'headline-md': ['"Noto Serif"'],
        'display-lg': ['"Noto Serif"'],
        'label-md': ['Manrope'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '400' }],
        button: ['14px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.8s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'fade-in': 'fadeIn 1s ease-out forwards',
      },
    },
  },
  plugins: [],
}
